services:
  postgres:
    container_name: postgres-sql-sg-citas-rembolsos
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1213
      POSTGRES_DB: sg_citas_rembolsos
    ports:
      - "5432:5432"
    volumes:
      #This is a named volume
      - postgres:/var/lib/postgres/data
    networks:
      - spring-boot-network

#Create the volume postgres
volumes:
  postgres:

#Create the network
networks:
  spring-boot-network:
    driver: bridge